Fix crash with a single-device configuration
writing:
```
devices: 0
```

in a configuration file was crashing because yaml parser would pass that as integer rather than a string:
```
Traceback (most recent call last):
  File "/root/furiosa-perf/.venv/lib/python3.12/site-packages/furiosa_perf/utils/config.py", line 105, in _create_config
    return config_class(**configs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 12, in __init__
  File "/root/furiosa-perf/.venv/lib/python3.12/site-packages/furiosa_perf/utils/config.py", line 66, in __post_init__
    self.tensor_parallel_size = len(self.devices.split(","))
                                    ^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'
```